### ISSUE TITLE
[08/12/2021] Third-party Usage: Swin-Transformer in Person Re-id

### ISSUE THREAD

**Issue by layumi** [microsoft/Swin-Transformer#110]
Thanks for the great repo. 

I applied the swin transformer to the person re-id baseline, and enabling training and testing.
The code is at here https://github.com/layumi/Person_reID_baseline_pytorch  

It would be great to involve the link in `README/Third-party Usage and Experiments`.  
Thanks a lot~

**Comment by ancientmooner** [comment]
Added, thanks!
