### ISSUE TITLE
[08/29/2021] Third-party Usage: Swin-Transformer in Low-level Vision (image restoration tasks including image super-resolution, denoising and compression artiact reduction)

### ISSUE THREAD

**Issue by JingyunLiang** [microsoft/Swin-Transformer#115]
Thanks for your great and elegant work.

We applied  Swin Transformer to image restoration tasks and dub it as SwinIR. It achieves state-of-the-art performance on six tasks, including classical/ lightweight/ real-world image super-resolution, color/grayscale image denoising and JPEG compression artifact reduction.

The code is available at https://github.com/JingyunLiang/SwinIR.

It would be great to add the link to README/Third-party Usage and Experiments. Let more people know this strong backbone for all kinds of vision tasks!

**Comment by caoyue10** [comment]
Added. Thanks for your great work!
