### ISSUE TITLE
How should I understand "all query patches within a  winodw share the same key set"?

### ISSUE THREAD

**Issue by ZhengfengLee** [microsoft/Swin-Transformer#118]
Hi, there. I have a little trouble in understanding the shared key set concept. I can't find any relative implementations, like fixing the key set, in codes. 
Could you tell me how should I understand "all query patches within a  winodw share the same key set which facilitates memory access in hardware"? 
Hope to hear from you soon.

**Comment by duduheihei** [comment]
Have the same question, hope to have a detailed description

**Comment by zeliu98** [comment]
This is compared with the traditional **sliding window** method. The following figure shows the difference:
![image](https://user-images.githubusercontent.com/46211709/145927557-58a90447-3baf-4bed-8d52-8e7d5937fc45.png)

- In traditional **sliding window** method. Different querys, **q** and **q**', will have different neighboring windows, which indicates different key sets. The computation is unfriendly to memory access and the real speed is thus not good. 
- In **non-overlapping window** method used in Swin Transformer. Different queries within a same red window, for example, **q** and **q'**, will share a same key set.

**Comment by ZhengfengLee** [comment]
> 

Thanks for your explanation. It helped me a lot.

**Comment by orram** [comment]
Hi there, 
Thanks for the explanation! How are these keys computed? 
For a window, there is a shared key; is it preset? or computed over the window? 

Thanks!
