### ISSUE TITLE
Dataset preparation

### ISSUE THREAD

**Issue by shwoo93** [microsoft/Swin-Transformer#120]
Thanks for sharing the code for this cool project.

I have an issue on setting the train/val data.
Could you provide more detailed descriptions on how to prepare the data?

- In a what way should I make the labeled sub-folders to set the standard folder-type dataset?
- How can we get the labels for the relative path to set the zip-type dataset? 

Are there any codes with helper functions to do these easily?

Thanks,

**Comment by jjqtony** [comment]
please refer to https://github.com/jkjung-avt/keras_imagenet
