### ISSUE TITLE
How to predict for Image Classification?

### ISSUE THREAD

**Issue by zhaowei0315** [microsoft/Swin-Transformer#121]
Hello Experts,
    Greeting.
    How to predict for Image Classification with trained checkopints?
    Thank you.

Best regards,
Felix

**Comment by zeliu98** [comment]
Hi, you can refer to the evaluation script:
https://github.com/microsoft/Swin-Transformer/blob/fa36255a62b37bc37c05133d7af5704b88d1ad3c/get_started.md?plain=1#L132-L146
