### ISSUE TITLE
about img_size parameter

### ISSUE THREAD

**Issue by btwbtm** [microsoft/Swin-Transformer#123]
Hi. I want to use swin-transformer as a backbone in my network. However, I find that there is an img_size parameter and subsequent operations are highly coupled with it. The input in my scenario is of arbitrary size. I wonder if there is an easy way to decouple this hard-code parameter? Thx!

**Comment by zeliu98** [comment]
Hi, you can refer to the object detection code for arbitrary size, where very little modification is required:
https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/master/mmdet/models/backbones/swin_transformer.py

**Comment by Kyfafyd** [comment]
> Hi, you can refer to the object detection code for arbitrary size, where very little modification is required: https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/master/mmdet/models/backbones/swin_transformer.py

Hi, if the only difference is in PatchEmbed?
https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/461e003166a8083d0b620beacd4662a2df306bd6/mmdet/models/backbones/swin_transformer.py#L429
