### ISSUE TITLE
How can I modify the num_classes?

### ISSUE THREAD

**Issue by Y1YU** [microsoft/Swin-Transformer#124]
Hello, I want to load the pretrained model you provided, and then train it on my dataset. 

So the problem is that after I create the model using `model = timm.create_model('swin_tiny_patch4_window7_224 num_classes=7)`, and then load your pretrained model, there is an error. Because the num_classes of your pretrained model is 1000, but I want 7.

So can anyone provide the solution for this problem?

**Comment by 8639sung** [comment]
I got same problem before.
Maybe you've already solved it.

---

I solve this problem like this.
```
state_dict = torch.load(checkpoint, map_location=device)['model']
temp = OrderedDict()
for n, v in state_dict.items():   # search all key from model
    name = n.replace("head.","")  # change key that doesn't match
    temp[name] = v
model.load_state_dict(temp, strict=False)
```

As you know setting "strict" as "false" can ignore key that not sufficient. ([document](https://tutorials.pytorch.kr/recipes/recipes/warmstarting_model_using_parameters_from_a_different_model.html?highlight=strict))
By change key's name that occur problem.
You can load model weight except that part.

**Comment by zeliu98** [comment]
Thanks @8639sung. You can also just delete it:
```python
state_dict = torch.load(checkpoint, map_location='cpu')['model']
del state_dict['head.weight']
del state_dict['head.bias']
```
