### ISSUE TITLE
[Not an issue, just to share some information] Be careful with DDPxSwin-Transformer

### ISSUE THREAD

**Issue by jeasinema** [microsoft/Swin-Transformer#132]
The model here has an internal buffer for storing `relative_position_index` (https://github.com/microsoft/Swin-Transformer/blob/main/models/swin_transformer.py#L103). With that, we need to set `broadcast_buffers=False` when constructing DDP(https://github.com/microsoft/Swin-Transformer/blob/main/main.py#L87). Or an Inplace error will be triggered.

Hope this helps if you use Swin-Transformer in your own tasks!

More context: https://github.com/pytorch/pytorch/issues/22095

**Comment by jeasinema** [comment]
Feel free to close this issue at any time @authors

**Comment by zeliu98** [comment]
Hi @jeasinema, thanks for pointing it!

**Comment by ancientmooner** [comment]
Thanks @jeasinema
