### ISSUE TITLE
Third-party Usage For Face Recognition

### ISSUE THREAD

**Issue by wang21jun** [microsoft/Swin-Transformer#142]
Thanks for your great work, we use Swin transformer for face recognition in our project, and Swin-S obtain a quite promising result of 98.17 in MegaFace rank1 protocol, which is the best accuracy in our project. More results, pretrained models and logs can be got from https://github.com/JDAI-CV/FaceX-Zoo/blob/main/training_mode/README.md

**Comment by zeliu98** [comment]
Very cool! I have added the link in README. Thanks a lot!
