### ISSUE TITLE
Questions on Swin backbone with FPN

### ISSUE THREAD

**Issue by DianCh** [microsoft/Swin-Transformer#153]
Hi! Thank you for releasing such a wonderful work. When you mentioned that the Swin backbone can be easily integrated with FPN (feature pyramid network), did you simply process the multi-level features with normal upsampling, convolution, and skip connection add? Are COCO object detection and ADE20k semantic segmentation experiments done with FPN?

**Comment by impiga** [comment]
Thanks for your interest in our work!

> did you simply process the multi-level features with normal upsampling, convolution, and skip connection add?

Yes, we adopt a standard FPN network.

> Are COCO object detection and ADE20k semantic segmentation experiments done with FPN?

Yes. For ADE20K, we use the UPerNet framework and it has a FPN-like component. For COCO object detection, we conduct experiments with different detectors and follow the original architecture designs of these frameworks. Most of them use FPN.

In addition, you can check [Swin-Transformer-Object-Detection](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection) and [Swin-Transoformer-Semantic-Segmentation](https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation) for our implementation of FPN in downstream tasks.

**Comment by DianCh** [comment]
I see. Thanks for the reply!
