### ISSUE TITLE
Training interrupted when training custom model?

### ISSUE THREAD

**Issue by feiyuhuahuo** [microsoft/Swin-Transformer#16]
I was using swin-tiny as the backbone of my model, but I encountered this error:

RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).

I did not modify any parameter after the model was wrapped by DDP. Do you know why?

**Comment by zeliu98** [comment]
Hi, the error says `your module has parameters that were not used in producing loss.` Would you like to share the code of your model? Or you can check if you have added some redundant modules that are not used (e.g. you add LN after output of each layer, but some are not used).

**Comment by feiyuhuahuo** [comment]
Hi, I have a simplified project.
https://pan.baidu.com/s/1g_iYvogO8YeMHwUOgBAvug
password: ac1b
Just run with `python -m torch.distributed.launch --nproc_per_node=1 --master_port=$((RANDOM)) train.py --train_bs=2`
The default backbone is swin-t, defined in  modules/yolact.py. And thus have the above problem.
You can modify the backbone to PVT-small or resnet101 by uncomment the two lines, which can train normally.
![图片](https://user-images.githubusercontent.com/32631344/114645547-48b63080-9d0c-11eb-8144-6fb24e991f14.png)

**Comment by zeliu98** [comment]
It seems that you only use the outputs of layer1~layer3 in FPN, but an additional LN is also added after layer0, which is not used:
`L539-L544` in `swin_transformer.py`
```python
            if i in self.out_indices:
                norm_layer = getattr(self, f'norm{i}')
                x_out = norm_layer(x_out)

                out = x_out.view(-1, H, W, self.num_features[i]).permute(0, 3, 1, 2).contiguous()
                outs.append(out)
```

**Comment by feiyuhuahuo** [comment]
Got it, thanks.
