### ISSUE TITLE
training from scratch using Imagenet-22k dataset

### ISSUE THREAD

**Issue by peiyingxin** [microsoft/Swin-Transformer#161]
get  an error 
<PIL.UnidentifiedImageError: Caught UnidentifiedImageError in DataLoader worker process 3. >
when i use imagenet-22K dataset .
have you plan to update code ,with training from scratch using Imagenet-22k dataset ?

hoping for your reply~thank you~

**Comment by caoyue10** [comment]
No plan yet.
