### ISSUE TITLE
Hi, does it support different height and width of patch as input, e.g. 224x288

### ISSUE THREAD

**Issue by XiaoqiWang** [microsoft/Swin-Transformer#163]
Hi, does it support different height and width of patch as input, e.g. 224x288

**Comment by XiaoqiWang** [comment]
Maybe set 7x9 window size for 224x288 patch size？

**Comment by caoyue10** [comment]
> Maybe set 7x9 window size for 224x288 patch size？

Setting 7x9 window size is a good idea.

**Comment by sulakshgupta988** [comment]
How can i set window size to 7x9 as window size is int but not a tuple?
