### ISSUE TITLE
Can we solve regression problems also?

### ISSUE THREAD

**Issue by sulakshgupta988** [microsoft/Swin-Transformer#167]
Is it possible to solve regression problems with SWIN? If it is how to do so?

Thank You So Much

**Comment by ancientmooner** [comment]
> Is it possible to solve regression problems with SWIN? If it is how to do so?
> 
> Thank You So Much

The backbone model architecture is orthogonal to task definition. It can be directly used for regression problems.

**Comment by nhathoang0110** [comment]
@sulakshgupta988  can you do it?
