### ISSUE TITLE
Corner patches high similarity

### ISSUE THREAD

**Issue by cazhang** [microsoft/Swin-Transformer#173]
Hi authors,

I tried to compute the cosine similarity of the pretrained swin-tiny output without average pooling. (7x7 patch each with 1000 dim)

The visualization below shows the patches at the four corners are highly correlated. Input image is the shown at the end. 

Is it due to the the 'relative position bias' or some special processing around the corner patches?

Could you help explain this?

![image](https://user-images.githubusercontent.com/3361026/153572455-2ffdbdf5-178a-4af8-a6c3-ed16281dcaa5.png)

**Comment by qkdkralsgh** [comment]
Hi, When I visualized the attention map, I also had a phenomenon with a high attention score in the corner like you. Do you know why?

**Comment by vb123er951** [comment]
hi, I also have this kind of results, does there have any update?
