### ISSUE TITLE
Where  are the ImageNet-22K pretrained models for Swin-V1-Tiny and Swin-V2-Small ?

### ISSUE THREAD

**Issue by Burrocode** [microsoft/Swin-Transformer#218]
Sorry, I can't found the download link in readme.md. Can you release the link and refresh the  readme.md？

**Comment by zeliu98** [comment]
Hi @Burrocode, you can find the links here: https://github.com/microsoft/Swin-Transformer/blob/91c54bf770d447eae4b7d2607add402684335fcd/README.md?plain=1#L101-L102

To be more specific, the link for Swin-V1-T-22K is https://github.com/SwinTransformer/storage/releases/download/v1.0.8/swin_tiny_patch4_window7_224_22k.pth, and the link for  Swin-V1-S-22K is https://github.com/SwinTransformer/storage/releases/download/v1.0.8/swin_small_patch4_window7_224_22k.pth
