### ISSUE TITLE
large resolution pretrain or fine-tune using resolution

### ISSUE THREAD

**Issue by dqshuai** [microsoft/Swin-Transformer#22]
hi,thanks for your project! i have some questions.
Does the structure of swin transformer limit its ability to fine-tune with a larger resolution? For example, similar to DeiT, it can use a lower training resolution and fine-tune the network at the larger resolution by interpolating the positional encoding.  Moreover,Is there a larger resolution pretrain model on imagenet22k(e.g 448)

**Comment by nauyan** [comment]
Have you been able to fine-tune the model using image sizes other than 224?

**Comment by ancientmooner** [comment]
@dqshuai @nauyan In Swin V1, we use bicubic interpolation to finetune on a different window size. In Swin V2, we develop a better approach to deal with different resolution in pre-training and fine-tuning.
