### ISSUE TITLE
Optimizer for the MoE experiments

### ISSUE THREAD

**Issue by a157801** [microsoft/Swin-Transformer#223]
It seems that the optimizer in main_moe.py is the original pytorch optimizer but not the TutelDistributedOptimizer in tutel, and experts with different parameters will be updated with shared gradient.

**Comment by zeliu98** [comment]
Hi @a157801, don't worry. Pytorch optimizer can automatically skip this synchronization by setting `_ddp_params_and_buffers_to_ignore`, like https://github.com/microsoft/Swin-Transformer/blob/91c54bf770d447eae4b7d2607add402684335fcd/main_moe.py#L88-L92
