### ISSUE TITLE
Question about continous relative positional bias (cpb)

### ISSUE THREAD

**Issue by hankyul2** [microsoft/Swin-Transformer#224]
Hi! Thank you for sharing your great work. I have question about continuous relative positional bias. (cpb)

My question is why positional coordinates are divided by `np.log2(8)`. Second question is why 8 is used in `np.log2()` not 9.

https://github.com/microsoft/Swin-Transformer/blob/91c54bf770d447eae4b7d2607add402684335fcd/models/swin_transformer_v2.py#L111

Thank you again!

**Comment by ancientmooner** [comment]
> Hi! Thank you for sharing your great work. I have question about continuous relative positional bias. (cpb)
> 
> My question is why positional coordinates are divided by `np.log2(8)`. Second question is why 8 is used in `np.log2()` not 9.
> 
> https://github.com/microsoft/Swin-Transformer/blob/91c54bf770d447eae4b7d2607add402684335fcd/models/swin_transformer_v2.py#L111
> 
> Thank you again!

The range of relative_coords_table is [-7,7], and 8 = 7 + 1 is the maximal numerator.

**Comment by hankyul2** [comment]
@ancientmooner Thank you for your reply.

Now I understand the reason for dividing `relative_coords_table + 1` by `np.log2(8)`. (maximal numerator)

But I still could not understand why numerator value should be 8 not 9. Because maxium value of `relative_coord_table` should be 8 not 7 by code shown in below code snippets. 
https://github.com/microsoft/Swin-Transformer/blob/91c54bf770d447eae4b7d2607add402684335fcd/models/swin_transformer_v2.py#L109

Thank you

hankyul
