### ISSUE TITLE
q @ k.transpose(-2, -1)   in swin_trasnformer.py?

### ISSUE THREAD

**Issue by henbucuoshanghai** [microsoft/Swin-Transformer#226]
@ means  torch.matmul???

**Comment by zeliu98** [comment]
Hi @henbucuoshanghai, you are right.

**Comment by henbucuoshanghai** [comment]
could u tell me why？

**Comment by mrkshllr** [comment]
If you refer to the '@' symbol itself, it stems from python (basically standard symbol for matrix multiplication);
You can take a look at e.g. https://legacy.python.org/dev/peps/pep-0465/ .
It's also been mentioned in pytorch if you look at the torch.bmm docu (https://pytorch.org/docs/stable/generated/torch.bmm.html?highlight=bmm#torch.bmm)

**Comment by mrkshllr** [comment]
This one might be more up-to-date for python actually: https://docs.python.org/3/library/operator.html#mapping-operators-to-functions

**Comment by henbucuoshanghai** [comment]
nice and kindly answer,tks
