### ISSUE TITLE
SwinV2-L 256 and SwinV2-L 384 have the same pertained weights uploaded for Imagenet 22k

### ISSUE THREAD

**Issue by ashutosh1807** [microsoft/Swin-Transformer#227]

**Comment by zeliu98** [comment]
Hi @ashutosh1807, they are exactly the same, which has been mentioned in README: 
https://github.com/microsoft/Swin-Transformer/blob/91c54bf770d447eae4b7d2607add402684335fcd/README.md?plain=1#L123-L124
