### ISSUE TITLE
How does Spatial MLP implement muti-head?

### ISSUE THREAD

**Issue by zhubingerdai** [microsoft/Swin-Transformer#268]
How does Spatial MLP implement muti-head? I don't understand this, isn't this just a conv1d? Why does it say: use group convolution to implement multi-head MLP?

**Comment by ancientmooner** [comment]
> How does Spatial MLP implement muti-head? I don't understand this, isn't this just a conv1d? Why does it say: use group convolution to implement multi-head MLP?

We find that using a linear mixer layer performs better than a 2-layer MLP. It is also faster.
