### ISSUE TITLE
Understanding: relative position bias

### ISSUE THREAD

**Issue by LoickCh** [microsoft/Swin-Transformer#281]
Hello,

I do not understand the implementation of "relative position bias" in SwinTransformer. I understand the theory: you parameterized a smaller bias matrix $\hat{B} \in \mathbb{R}^{(2M-1) \times (2M-1)}$ and you take values of $B$ in $\hat{B}$. 
```python
self.relative_position_bias_table = nn.Parameter(torch.zeros((2 * win_h - 1) * (2 * win_w - 1), num_heads))
```
In practice, my question is the following: why get_relative_position_index returns the following matrix ? Why the relative position matrix is the following and not another order ? 
```python
>>> get_relative_position_index(2,2)
tensor([[4, 3, 1, 0],
        [5, 4, 2, 1],
        [7, 6, 4, 3],
        [8, 7, 5, 4]])
```

I can imagine plenty of indexing and this one is not the first that comes in my mind, so I guess there is an idea behind that I do not understand.

Thanks in advance, :)

**Comment by LoickCh** [comment]
Is the answer related to _Rethinking and Improving Relative Position Encoding for Vision Transformer_, (SM, Fig.6) about euclidian method ?

**Comment by Andyyoung0507** [comment]
Thank you. This answer helps.
