### ISSUE TITLE
Accuracy curve for each epoch

### ISSUE THREAD

**Issue by WangFeng18** [microsoft/Swin-Transformer#29]
Thanks for providing the excellent work.  I am trying to reproduce the results of Swin-T model. Could you please provide a accuracy curve w.r.t epochs, which can serve as a reference for me to validate the correctness of codes and experiments.

Thanks a lot!

**Comment by zeliu98** [comment]
Hi, here is the training log of `Swin-T`, you can take it as reference. 
[log_rank0.txt](https://github.com/microsoft/Swin-Transformer/files/6328720/log_rank0.txt)

**Comment by WangFeng18** [comment]
Cool, thank you!

**Comment by starmemda** [comment]
Thank you very much!

**Comment by JaminFong** [comment]
Thanks for your great work. Could you please also provide the logs of the other models, e.g. Swin-S, -B? Thank you so much in advance!
