### ISSUE TITLE
What about the speed of object detection model?

### ISSUE THREAD

**Issue by yangbisheng2009** [microsoft/Swin-Transformer#31]

**Comment by lucky-xu-1994** [comment]
have you test the inference speed of the object detection model? if yes, thank you for sharing!

**Comment by lucky-xu-1994** [comment]
@yangbisheng2009  
have you test the inference speed of object detection model? if yes, thank you for sharing!

**Comment by yangbisheng2009** [comment]
> @yangbisheng2009
> have you test the inference speed of object detection model? if yes, thank you for sharing!
I have not test it. Guess it will be slow because it based on maskrcnn.

**Comment by ancientmooner** [comment]
please try testing the speed of models on your machine using a codebase: https://github.com/SwinTransformer/Swin-Transformer-Object-Detection
