### ISSUE TITLE
share baidu-yun passwd to extract pretrained files?

### ISSUE THREAD

**Issue by ignitemylife** [microsoft/Swin-Transformer#32]
as is said in tittle, could u plz share the baiduyun code to extracte the pretrained ckpt files? I found that it is really too slow for me to download ckpts using github urls. T.T

**Comment by impiga** [comment]
Hi, as the note below [this table](https://github.com/microsoft/Swin-Transformer#main-results-on-imagenet-with-pretrained-models) indicates, the access code for baiduyun is swin.

**Comment by ignitemylife** [comment]
Oops,  I ignore this prompt somehow. Really thanks.
