### ISSUE TITLE
train and infer on different input sizes

### ISSUE THREAD

**Issue by iariav** [microsoft/Swin-Transformer#34]
Hi,
thanks for releasing this awesome repo.

I wanted to know if it is possible to train on input with a certain resolution and then run inference on inputs with variable resolutions (smaller\larger than the resolution used for training). 
just to clarify - I mean without resizing\croping the input to the training resolution during inference.

thanks

**Comment by ancientmooner** [comment]
@iariav @junyongyou In original Swin paper, we use bicubic interpolation to hand different window size. In Swin V2, we use continuous relative position bias instead.

**Comment by ancientmooner** [comment]
Swin V2 has discussed how to use a different window size in inference than that in training
