### ISSUE TITLE
Where to download CityscapesDataset

### ISSUE THREAD

**Issue by walynlee** [microsoft/Swin-Transformer#36]
Dear author:
when I run the train.py:
errors happened:
FileNotFoundError:CityscapesDataset:No such file or directory:'data/cityscapes/leftImg8bit/train'

**Comment by TiankaiHang** [comment]
Maybe you could use the scripts from PaddlePaddle.
`https://github.com/PaddlePaddle/PaddleSeg/blob/f48739b1dc0107807fecb898422fed5d7a414f9c/dataset/download_cityscapes.py`
