### ISSUE TITLE
error about apex.amp

### ISSUE THREAD

**Issue by Lg955** [microsoft/Swin-Transformer#37]
I used the ` "pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext"` ./" to install apex.   

 when I `"from apex import amp",` the error is `"ModuleNotFoundError: No module named 'amp'"`.

My solution is `"pip install -v --no-cache-dir ./"`,  then everything is OK !!!!

**Comment by zeliu98** [comment]
Thanks, that's great!
