### ISSUE TITLE
If I can train out the performance in the paper with the default configuration?

### ISSUE THREAD

**Issue by starmemda** [microsoft/Swin-Transformer#39]
Hello! I have tried the default config with swin_tiny_224 to train without any pre-training model. And in the 65-th epoches, the top1 get to 71.3. I wonder whether I can get the performance like 81.5 as the paper say ? After all, it really takes too long time to train.

**Comment by zeliu98** [comment]
Hi, you can refer to the training log in this issue #29 . Note the log used 16GPUs with total batch-size of 1024 and got 81.3 acc.

**Comment by starmemda** [comment]
中科大有和亚研院有合作项目？

**Comment by starmemda** [comment]
感谢老哥

**Comment by ancientmooner** [comment]
> 中科大有和亚研院有合作项目？
Yes, there are joint ph.D programs between USTC and MSRA.
