### ISSUE TITLE
Model inference with TorchServe

### ISSUE THREAD

**Issue by kamalkraj** [microsoft/Swin-Transformer#40]
https://github.com/kamalkraj/Swin-Transformer-Serve

**Comment by ancientmooner** [comment]
Could you please report the accuracy numbers and provide trained models in your new repository, so as to facilitate others to get sense of correctness and model behavior? Then we will merge the pull requests in.

**Comment by kamalkraj** [comment]
Updated https://github.com/kamalkraj/Swin-Transformer-Serve/blob/master/README.md
