### ISSUE TITLE
an issue in image classification code --swin_transformer

### ISSUE THREAD

**Issue by reacher-l** [microsoft/Swin-Transformer#42]
![image](https://user-images.githubusercontent.com/45810596/115492329-30a65a00-a294-11eb-9c9d-f7cca0e6c761.png)

            mask_windows = window_partition(img_mask, self.window_size)  # nW, window_size, window_size, 1
            mask_windows = mask_windows.view(-1, self.window_size * self.window_size)
            attn_mask = mask_windows.unsqueeze(1) - mask_windows.unsqueeze(2)                                              # i think its error here !!!!!!!!!!!
            attn_mask = attn_mask.masked_fill(attn_mask != 0, float(-100.0)).masked_fill(attn_mask == 0, float(0.0))

 attn_mask = mask_windows.unsqueeze(2) - mask_windows.unsqueeze(1)

**Comment by reacher-l** [comment]
![image](https://user-images.githubusercontent.com/45810596/115492522-80852100-a294-11eb-9077-440430dd3bd7.png)



should it be consistent with this

**Comment by zeliu98** [comment]
Hi, it doesn't matter. The `attn_mask` of 
```python
attn_mask = mask_windows.unsqueeze(1) - mask_windows.unsqueeze(2)
attn_mask = attn_mask.masked_fill(attn_mask != 0, float(-100.0)).masked_fill(attn_mask == 0, float(0.0))
```
and 
```python
attn_mask = mask_windows.unsqueeze(2) - mask_windows.unsqueeze(1)
attn_mask = attn_mask.masked_fill(attn_mask != 0, float(-100.0)).masked_fill(attn_mask == 0, float(0.0))
```
is exactly the same

**Comment by reacher-l** [comment]
Yes, they are exactly the same. hh
