### ISSUE TITLE
1k model in the ImageNet-22k pre-trained models?

### ISSUE THREAD

**Issue by jinwon-samsung** [microsoft/Swin-Transformer#43]
https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_base_patch4_window7_224_22kto1k.pth\

What does the models under the 1k model column in the ImageNet-22k pre-trained models mean?

Does it mean that it is pre-trained under the Imagent-22k and then trained on the 1k model?

**Comment by zeliu98** [comment]
Yes, you are right. And you can find the only 22k pretrained weight from the 22K model column.
