### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by vvhj** [microsoft/Swin-Transformer#45]
How can I get the  following dataset？

data
└── ImageNet-Zip
    ├── train_map.txt
    ├── train.zip
    ├── val_map.txt
    └── val.zip

We are now using the standard folder dataset, the speech of which is slow, about 2 hours/ 1 epoch.

**Comment by zeliu98** [comment]
Hi, you can get the `train.zip` and `val.zip` by zipping the train and val folder by yourself. And then create the `train_map.txt`, `val_map.txt` to store the relative path in the corresponding zip file and ground truth label. You can see https://github.com/microsoft/Swin-Transformer/blob/main/get_started.md#data-preparation for more  example.

**Comment by eadwu** [comment]
Where can I get the ground truth labels used?

I can't seem to find the labels used in the example given.
```
❯  rg n01440764 tmp
tmp/ILSVRC/devkit/data/map_clsloc.txt
449:n01440764 449 tench

tmp/ILSVRC2015/devkit/data/map_clsloc.txt
449:n01440764 449 tench
```

Getting a label of 449 for n01440764 instead of 0.

**Comment by youzhaxiaomayi** [comment]
I tried to test the author's model and I had the same problem.

**Comment by youzhaxiaomayi** [comment]
> I tried to test the author's model and I had the same problem.
I got it.  The author uses caffe-Imagnet's label.[http://dl.caffe.berkeleyvision.org/caffe_ilsvrc12.tar.gz](url)

**Comment by youzhaxiaomayi** [comment]
> > I tried to test the author's model and I had the same problem.
> > I got it.  The author uses caffe-Imagnet's label.[http://dl.caffe.berkeleyvision.org/caffe_ilsvrc12.tar.gz](url)

Accroding to my actual tests, instead of using the above labels, the author actually uses the following one[https://raw.githubusercontent.com/soumith/imagenetloader.torch/master/valprep.sh
](https://raw.githubusercontent.com/soumith/imagenetloader.torch/master/valprep.sh
)

**Comment by jjqtony** [comment]
> 

The valprep.sh has no anything about train_map.txt and val_map.txt!

**Comment by jjqtony** [comment]
Could the author upload the train_map.txt and val_map.txt?

**Comment by ZSL98** [comment]
LOL
