### ISSUE TITLE
Some problem about relative Position Embedding

### ISSUE THREAD

**Issue by yan-hao-tian** [microsoft/Swin-Transformer#46]
Hello. I find the implementation of relative **PE** is different from the description in the paper "Self-Attention with Relative Position Representations". So, could you introduce a little more about how you do to implement it please? Thanks a lot.

**Comment by ancientmooner** [comment]
Please check the code at:
https://github.com/microsoft/Swin-Transformer/blob/main/models/swin_transformer.py#L126

This kind of PE is simpler than the method you mentioned, but is also effective. I did not see places which compare this approach to the method in the paper you mentioned. These approach has been also used in early works exploring application in vision (i.e. relation networks and local relation networks). It is also used by Google's T5 model and Microsoft's UniLM v2. You can find description in the Swin paper or these earlier papers.
