### ISSUE TITLE
APEX Gradient overflow

### ISSUE THREAD

**Issue by vvhj** [microsoft/Swin-Transformer#47]
When I use the O1 train the swin-net, but
`Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 131072.0
[2021-04-25 05:35:19 swin_base_patch4_window7_224](main_prune.py 310): INFO Train: [0/300][4050/5004]   eta 0:17:06 lr 0.000500 time 1.1737 (1.0765)    loss 3.2572 (3.3279)    grad_norm 1.0323 (nan)  mem 4814MB`

Is this normal?

**Comment by Nuckijfuta** [comment]
[recert
]()

**Comment by zeliu98** [comment]
Hi, there is no need to worry, it's normal, since apex use a `dynamic` loss scale.  You can ref to the [Doc](https://nvidia.github.io/apex/amp.html) for more detail.

**Comment by vvhj** [comment]
> Hi, there is no need to worry, it's normal, since apex use a `dynamic` loss scale. You can ref to the [Doc](https://nvidia.github.io/apex/amp.html) for more detail.

That is right, thank you.

**Comment by vvhj** [comment]
This may be an offensive request. Could I get a training log from you? I'm trying to prune the swin transformer and want to make a comparison. If this is not realistic, forget it and appreciate your help！

**Comment by zeliu98** [comment]
Hi, please refer to this issue #29 for the training log.
