### ISSUE TITLE
Model inference speed

### ISSUE THREAD

**Issue by lichunxiang93** [microsoft/Swin-Transformer#48]
Hello, thank you for sharing. When testing the model inference speed, I used your swin_tiny_patch4_window7_224.pth, but the inference time of my 224x224 tensor input on V100 is about 15ms, which is a bit different from the speed of 755.2/s in the paper.
![image](https://user-images.githubusercontent.com/30490690/115987288-08499300-a5e7-11eb-8cf3-95ff844c60d4.png)
![image](https://user-images.githubusercontent.com/30490690/115987300-10a1ce00-a5e7-11eb-8f5f-387faaa3d1aa.png)
![image](https://user-images.githubusercontent.com/30490690/115987311-1d262680-a5e7-11eb-8d4e-80bbab203306.png)
May I ask where I deal with the problem? 
![image](https://user-images.githubusercontent.com/30490690/115987744-e7823d00-a5e8-11eb-82f9-e8f7a8872278.png)

**Comment by zeliu98** [comment]
Hi, following other works we use a much larger batch-size (like 64) to measure the throughput. Besides, we have also provided a [script](https://github.com/microsoft/Swin-Transformer/blob/main/get_started.md#throughput) to measure the throughput .
