### ISSUE TITLE
checkpoint of Swin-Large trained on ImageNet-1K only

### ISSUE THREAD

**Issue by tonysy** [microsoft/Swin-Transformer#49]
Hi,
Could you share the checkpoint of Swin-Large trained on ImageNet-1K only?
ImageNet-22k is too difficult to get.

Thanks a lot.

**Comment by ancientmooner** [comment]
We did not train Swin-Large on ImageNet-1K. Welcome to train it yourself and share it back to us. We will acknowledge on that.

**Comment by syorami** [comment]
> Hi, Could you share the checkpoint of Swin-Large trained on ImageNet-1K only? ImageNet-22k is too difficult to get.
> 
> Thanks a lot.

hi, did you train the Swin-L on ImageNet-1K? What's the final results?

**Comment by ancientmooner** [comment]
@syorami please find https://github.com/microsoft/SimMIM for ImageNet-1K pre-trained model. But it must be combined with self-supervised pre-training to work well.

**Comment by ancientmooner** [comment]
@syorami SimMIM paper has numbers: 83.5 (w.o. self-sup) vs 85.4 (with self-sup)

**Comment by syorami** [comment]
> @syorami SimMIM paper (https://arxiv.org/pdf/2111.09886.pdf) has the numbers: 83.5 (w.o. self-sup) vs 85.4 (with self-sup)

Thanks for the information!
