### ISSUE TITLE
the source code for classification has run through(关于分类的源码已经跑通)

### ISSUE THREAD

**Issue by lianjizhe** [microsoft/Swin-Transformer#59]
https://www.jianshu.com/p/d50c1855e583
This is a blog introduction on how to run through the code, let's talk a lot. （这是如何跑通代码的博客介绍，大家多多交流）

**Comment by wangcong9299** [comment]
分布式的跑起来了吗兄弟

**Comment by wangcong9299** [comment]
> https://www.jianshu.com/p/d50c1855e583
> This is a blog introduction on how to run through the code, let's talk a lot. （这是如何跑通代码的博客介绍，大家多多交流）

分布式的跑起来了吗兄弟

**Comment by ancientmooner** [comment]
Thanks @lianjizhe
