### ISSUE TITLE
How to use own datasets train model

### ISSUE THREAD

**Issue by chekistcccp** [microsoft/Swin-Transformer#60]
How to use own datasets train model

**Comment by zeliu98** [comment]
Hi, we mostly rely on the torchvision `ImageFolder` dataset which you can find here: https://github.com/microsoft/Swin-Transformer/blob/43791e206d0ef5464798e81e33ff74ba171636d2/data/build.py#L82-L83
For your own datasets, you can simply replace it and make sure your data is placed in this way:
```
root/class1/xxx.png
root/class1/xxy.png
root/class1/[...]/xxz.png

root/class2/123.png
root/class2/nsdf3.png
root/class2/[...]/asd932_.png
```

For more advanced usage you can follow the tutorial: https://pytorch.org/tutorials/beginner/basics/data_tutorial.html?highlight=dataset.
