### ISSUE TITLE
Sharing about running segmentation code(开源的分割代码跑通了，数据集分享在下面)

### ISSUE THREAD

**Issue by lianjizhe** [microsoft/Swin-Transformer#63]
https://www.jianshu.com/p/8d4f73d0471a
This is a blog introduction about how to run through the code. It also shares data sets and models. You can refer to it if necessary, and communicate more.  (怎么跑通代码以及数据集的分享都在上面的博客链接)

**Comment by ancientmooner** [comment]
Thanks
