### ISSUE TITLE
seek of closed file

### ISSUE THREAD

**Issue by jianghaoyuan1994** [microsoft/Swin-Transformer#66]
Hi guys, I find a bug. 
https://github.com/microsoft/Swin-Transformer/blob/bc26f4764735a91b0330071cc9ca9ffcf60340fa/data/cached_image_folder.py#L185-L188
If the program runs to here, it will raise "seek of closed file" error. I think should add return img.convert('RGB') inside the with region:
```python
    else:
        with open(path, 'rb') as f:
            img = Image.open(f)
            return img.convert('RGB')
    return img.convert('RGB')
```

**Comment by zeliu98** [comment]
Thanks for pointing it! We will fix it.
