### ISSUE TITLE
Augmentations for data (timm.data.create_transform: randaugment)

### ISSUE THREAD

**Issue by Hayoung93** [microsoft/Swin-Transformer#67]
Thank you for your great work.

I have a question about the code:

As `timm.data.create_transform` returns `timm.data.auto_augment.RandAugment` object, I checked the behavior of this object by passing the same image twice to this object and get different results. Therefore it seems that different augmentations (randaugment) are applied for each mini-batch.

I wonder I understood correctly. Thanks.

**Comment by zeliu98** [comment]
Yes, you are right~
