### ISSUE TITLE
About Training Time

### ISSUE THREAD

**Issue by wangjk666** [microsoft/Swin-Transformer#68]
Hi, thanks a lot for your amazing work! I have tried to train Swin-Transformer from scratch on ImageNet1k, but it took me quite a long time,  so I  wonder how long did it take you to train the base model on ImageNet 1k and what kind of GPUs did you use?

**Comment by ChongjianGE** [comment]
Hi @wangjk666, I also met the problem. It took me around 1 hour/epoch on 8 V100 GPUs to train the base model on ImageNet-1k. What about your training time?

**Comment by zeliu98** [comment]
Hi, we use 16xV100 to train the base model which takes about 12m per epoch on ImageNet-1K.

**Comment by wangjk666** [comment]
> Hi @wangjk666, I also met the problem. It took me around 1 hour/epoch on 8 V100 GPUs to train the base model on ImageNet-1k. What about your training time?

Hi, I trained on 8 3090ti GPUs, and it took me about 3 days to train the base model.

**Comment by flybiubiu** [comment]
> > 嗨@wangjk666，我也遇到了这个问题。我在 8 个 V100 GPU 上花费了大约 1 小时/周期在 ImageNet-1k 上训练基本模型。你的训练时间呢？
> 
> 嗨，我在 8 个 3090ti GPU 上训练，我花了大约 3 天时间来训练基础模型。

3090ti？？？？

**Comment by brown-cats** [comment]
> > > 嗨@wangjk666，我也遇到了这个问题。我在 8 个 V100 GPU 上花费了大约 1 小时/周期在 ImageNet-1k 上训练基本模型。你的训练时间呢？
> > 
> > 
> > 嗨，我在 8 个 3090ti GPU 上训练，我花了大约 3 天时间来训练基础模型。
> 
> 3090ti？？？？
May i ask what wrong with 3090ti?

**Comment by Sissuire** [comment]
So, how you guys boost the training efficiency? It takes me 1 hour per epoch... 
Would training with .zip files work better ? Or just more GPUs... @wangjk666 @flybiubiu

**Comment by Barbhuiya12** [comment]
Hi would guys find any optimization techniques to reduce its training time
