### ISSUE TITLE
Training on multiple image size

### ISSUE THREAD

**Issue by dsshim0125** [microsoft/Swin-Transformer#69]
Hi, 

I've really appreciated all your works.

I found that if the shape of the window is fixed to the square which is the assumption of this repository code, it is really hard to resize the input size.

If the length of depth is 4, then the window_size should be the common divisor of (H//patch_size//8, W//patch_size//8).

I want the input size of (192, 640) but as following, the largest size of the window becomes 2 with the patch_size of 4 which is too small to capture global attention.

So, the question is how can I change the shape of the window from the square to the rectangle?

I'm very looking forward to your answer.

Thank you!

**Comment by zeliu98** [comment]
Hi, you can ref to the [detection](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection) and [segmentation](https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation) code where the input is also non-square and variable. You can also using non-square window by modifying some code (where the window-size is used).
