### ISSUE TITLE
How can I download pre-trained model if I can't register on baidu?

### ISSUE THREAD

**Issue by tdain72** [microsoft/Swin-Transformer#71]
I want to download the pre-trained model, but I don't have a Chinese mobile phone number so I can't create an account of baidu. Can you upload it to google drive ?

**Comment by zeliu98** [comment]
Hi, you can find the models from the direct link of github, like:
![image](https://user-images.githubusercontent.com/46211709/124482658-18969f00-dddc-11eb-9164-7a6e9e6c0f4b.png)
