### ISSUE TITLE
Question about CLIP_GRAD

### ISSUE THREAD

**Issue by liuzhuang13** [microsoft/Swin-Transformer#73]
Thanks for sharing the code and the great work!

I wonder what value of CLIP_GRAD should be set, since the default value in config.py is 5.0 and the paper says "and gradient clipping with a max norm of 1 are used". Thanks in advance

**Comment by zeliu98** [comment]
Hi, we found the average grad-norm is larger than 1.0 (about 4.0) so we changed the CLIP_GRAD to a bigger value to do as little grad-clipping as possible. But the performance don't have much difference.
