### ISSUE TITLE
Question about relative position bias

### ISSUE THREAD

**Issue by Cieeiee** [microsoft/Swin-Transformer#75]
https://github.com/microsoft/Swin-Transformer/blob/bc26f4764735a91b0330071cc9ca9ffcf60340fa/models/swin_transformer.py#L101

Why do you multiply by  `2 * self.window_size[1] - 1` in position bias?

**Comment by zeliu98** [comment]
Hi, pytorch doesn't support 2d indexing (using x, y) so we first reformat the 2d index tensor to a 1d index tensor for indexing the `relative_position_bias_table`. The usage can be found here: https://github.com/microsoft/Swin-Transformer/blob/43791e206d0ef5464798e81e33ff74ba171636d2/models/swin_transformer.py#L126-L127
