### ISSUE TITLE
Request help to resolve "No rendezvous handler" error on Windows 10

### ISSUE THREAD

**Issue by thetushar006** [microsoft/Swin-Transformer#77]
Hi, I am trying to run the scripts on Windows 10 on PyCharm. My computer has a single GPU card (RTX 2080Ti). I have followed the get_started guide to setup my environment and am trying to evaluate the pre-trained swin-tiny model using the sample parameters mentioned in the get_started document:
--nproc_per_node 1 --master_port 12345 main.py --eval \ --cfg configs/swin_tiny_patch4_window7_224.yaml --resume swin_tiny_patch4_window7_224.pth --data-path <data_path> --local_rank 0 --amp-opt-level O0

However, I get the following error. 
raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
RuntimeError: No rendezvous handler for env://

I tried to search online to resolve the error. From what I understand, this is because of Windows 10 (https://github.com/PyTorchLightning/pytorch-lightning/issues/5358). When I ran the codes on my GPU server running Ubuntu, I was able to run the codes without encountering this error. However I would still like to run the codes on my Windows machine. Could you please suggest what modifications I should make to my setup/code to resolve this error on Windows 10? 

Thanks very much!

**Comment by Tz-KangNi** [comment]
I have the same question, are you resolving this error on Windows 10? Thank you very much
