### ISSUE TITLE
RuntimeError: expected a single top-level function

### ISSUE THREAD

**Issue by fmy7834** [microsoft/Swin-Transformer#78]
File "/home/fumy/anaconda3/envs/CloserLookFewShot/lib/python3.6/site-packages/torch/jit/frontend.py", line 144, in get_jit_ast
    raise RuntimeError("expected a single top-level function")
Is there anybody meet this question?

**Comment by l9761116** [comment]
exm, i've met the same problem. did you suceed in solving it?

**Comment by fmy7834** [comment]
I met this problem again yesterday and found this is about the edition of torch and timm package. I used torch 1.7.1 and timm 0.3.2.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/Swin-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 晚上7:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/Swin-Transformer] RuntimeError: expected a single top-level function (#78)





 
exm, i've met the same problem. did you suceed in solving it?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by l9761116** [comment]
Thanks! It work!

**Comment by laomagic** [comment]
hello, i've met the same problem. did you suceed in solving it?

**Comment by fmy7834** [comment]
I have solved the error and found this is about the edition of torch and timm package. I use torch 1.7.1 and timm 0.3.2, it works.



---Original---
From: ***@***.***&gt;
Date: Fri, Dec 17, 2021 23:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [microsoft/Swin-Transformer] RuntimeError: expected a singletop-level function (#78)




 
hello, i've met the same problem. did you suceed in solving it?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ancientmooner** [comment]
@fmy7834 thanks!
