### ISSUE TITLE
What is the difference between ImageNet21K and ImageNet22K?

### ISSUE THREAD

**Issue by uniyushu** [microsoft/Swin-Transformer#79]
I just wonder what is the difference between [ImageNet21K](https://github.com/Alibaba-MIIL/ImageNet21K) and ImageNet22K.Is that an approximation?

**Comment by 675492062** [comment]
1K && 22K here, It's obviously a matter of the amount of training data

**Comment by yuleung** [comment]
same question....

**Comment by yuleung** [comment]
same confuse..

**Comment by yuleung** [comment]
same confusion..

**Comment by yuleung** [comment]
ImageNet Fall 2011 is 22k
