### ISSUE TITLE
I hope u the code could be ran in a single gpu. From a pool postgraduate...

### ISSUE THREAD

**Issue by BrotherHappy** [microsoft/Swin-Transformer#8]
It is a interesting and may be the revolution of CNN

**Comment by ancientmooner** [comment]
Thanks for your interest and positive comments. The code can well support 1 GPU for even large batch by the "--accumulation-steps" argument. But you have to wait longer to get the results :(

**Comment by AnthonyFang623** [comment]
Thank you for sharing this to let us know this amazing job, but could you give a example about how to run this model with single GPU please?

**Comment by YongboLiang** [comment]
> 



> 

hi，do you solve that? I meet this problem, too. thans
