### ISSUE TITLE
How to load the pretrained model

### ISSUE THREAD

**Issue by Williamlizl** [microsoft/Swin-Transformer#83]

**Comment by wdayang** [comment]
models are trained on 8 GPUs, you need to have the 8 GPUs first then load the model, or will report errors: unexpected keys in state _dict: 'model'.
I don't have that many GPU, thus give up.

**Comment by zeliu98** [comment]
Hi,  we have provided the code here: https://github.com/microsoft/Swin-Transformer/blob/43791e206d0ef5464798e81e33ff74ba171636d2/utils.py#L19-L43

**Comment by zeliu98** [comment]
> models are trained on 8 GPUs, you need to have the 8 GPUs first then load the model, or will report errors: unexpected keys in state _dict: 'model'.
> I don't have that many GPU, thus give up.

Hi @wdayang, you don't need 8 GPUs. It seems you mistook the the **checkpoint** as the state_dict. You should firstly get the state_dict from the checkpoint (which is a dict containes the state_dict) by the key **'model'** like: 
 `state_dict=checkpoint['model']`

**Comment by wdayang** [comment]
> > models are trained on 8 GPUs, you need to have the 8 GPUs first then load the model, or will report errors: unexpected keys in state _dict: 'model'.
> > I don't have that many GPU, thus give up.
> 
> Hi @wdayang, you don't need 8 GPUs. It seems you mistook the the **checkpoint** as the state_dict. You should firstly get the state_dict from the checkpoint (which is a dict containes the state_dict) by the key **'model'** like:
> `state_dict=checkpoint['model']`

Ok, @zeliu98 thanks for resolve the confusion. I will try later.

**Comment by layumi** [comment]
Hi @Williamlizl 

Here I just provide one simple way via the third party (https://github.com/rwightman/pytorch-image-models).

```python
import timm
model_ft = timm.create_model('swin_base_patch4_window7_224', pretrained=True)
x = model_ft.forward_features(x)
```

Make sure you have the pytorch >= 1.7.0

**Comment by wdayang** [comment]
> Hi @Williamlizl
> 
> Here I just provide one simple way via the third party (https://github.com/rwightman/pytorch-image-models).
> 
> ```python
> import timm
> model_ft = timm.create_model('swin_base_patch4_window7_224', pretrained=True)
> x = model_ft.forward_features(x)
> ```
> 
> Make sure you have the pytorch >= 1.7.0

Yes, this works fine, thanks.

**Comment by PangXuejiao** [comment]
> > Hi @Williamlizl
> > Here I just provide one simple way via the third party (https://github.com/rwightman/pytorch-image-models).
> > ```python
> > import timm
> > model_ft = timm.create_model('swin_base_patch4_window7_224', pretrained=True)
> > x = model_ft.forward_features(x)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Make sure you have the pytorch >= 1.7.0
> 
> Yes, this works fine, thanks.

Hello, can you explain in detail how to solve the problem of pre-training weights?
Thank you very much

**Comment by layumi** [comment]
@PangXuejiao 
When you use the third party code, it will perform like the official pytorch ResNet50 to download the model weight and put the weight into the pre-defined network structure.
