### ISSUE TITLE
what is the stochastic depth augmentation when training swin-l-224 in imagenet22k and finetune swin-l-384 in imagenet1k?

### ISSUE THREAD

**Issue by jiandan42** [microsoft/Swin-Transformer#86]
Thanks for the excellent work! 
  The paper only gives the stochastic depth augmentation of training swin-t, swin-s and swin-b on imagenet-1k,. The stochastic depth augmentation for imagenet22k swin-l-224 training and imagenet1k swin-l-384 finetuning is unclear. Could you  provide these hyper-parameters?

**Comment by ancientmooner** [comment]
We did not change drop path rate between pre-training and fine-tuning on image classification. For training on imagenet-22k, we use 0.2 for both Swin-B and Swin-L.
