### ISSUE TITLE
Intuition for reducing Swin in size

### ISSUE THREAD

**Issue by FrankBrongers** [microsoft/Swin-Transformer#88]
Thanks for the great work!

I was wondering if you had any tips or intuitions for reducing the Swin model even further. In the paper you mention the tiny version is comparable to the ResNet-50 in terms of computational complexity. What would you trim from the tiny version first to bring the complexity more in line with a ResNet-18? And would this be different for the detection and semantic segmentation versions?

**Comment by ancientmooner** [comment]
you may reduce the channel from 96 to 64. This should have similar complexity with that of ResNet-18.

**Comment by FrankBrongers** [comment]
Thank you!
