### ISSUE TITLE
A question about qk_scale

### ISSUE THREAD

**Issue by Sample-design-alt** [microsoft/Swin-Transformer#94]
Hello, I have a question about this:
https://github.com/microsoft/Swin-Transformer/blob/2622619f70760b60a42b996f5fcbe7c9d2e7ca57/models/swin_transformer.py#L123

what's the function of scale ? Or I can find the reason in paper?

Thanks.

**Comment by zeliu98** [comment]
You can find the reason in paper [Attention is All you Need](https://arxiv.org/pdf/1706.03762.pdf). In Section 3.2.1, the author says "...We suspect that for large values of dk, the dot products grow large in magnitude, pushing the softmax function into regions where it has extremely small gradient. To counteract this effect, we scale the dot products by 1/sqrt(dk)."

**Comment by Sample-design-alt** [comment]
> You can find the reason in paper [Attention is All you Need](https://arxiv.org/pdf/1706.03762.pdf). In Section 3.2.1, the author says "...We suspect that for large values of dk, the dot products grow large in magnitude, pushing the softmax function into regions where it has extremely small gradient. To counteract this effect, we scale the dot products by 1/sqrt(dk)."
Hello @zeliu98 ,
I have got it. Thanks for your reply!
The issue can be closed.
